apiVersion: network.harvesterhci.io/v1beta1
kind: ClusterNetwork
metadata:
  name: ext-bond
---
apiVersion: network.harvesterhci.io/v1beta1
kind: VlanConfig
metadata:
  name: ext-bond-config
spec:
  clusterNetwork: ext-bond
  uplink:
    nics:
      - ens19
      - ens20
    bondOptions:
      mode: active-backup
      miimon: 100
