apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: subnetexternal
spec:
  cidrBlock: 10.0.0.0/16
  default: false
  enableLb: true
  excludeIps:
  - 10.0.0.1..10.0.58.255
  - 10.0.59.101..10.0.255.254
  gateway: 10.0.10.1
  gatewayNode: ""
  natOutgoing: true
  private: false
  protocol: IPv4
  provider: vswitchexternal.kube-system.ovn
  vpc: nat-vpc
  vlan: vlan-external

